remote_theme: broccolini/swiss
title: Vaishak Belle 
# description: Faculty at University of Edinburgh 
#baseurl: "" # the subpath of your site, e.g. /blog
# url: "vaishakbelle.github.io" # "vaishakbelle.com" # the base hostname & protocol for your site, e.g. http://example.com
#github_repo: vaishakbelle.github.io # the GitHub repo name for your project
#github_username: vaishakbelle
github_repo:  # the GitHub repo name for your project
github_username: vaishakbelle

# Optional social link, you can choose from the following options:
# twitter (default), instagram, medium, or dribbble
social_link: twitter
social_username: vaishakbelle

# Set theme color here
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.
theme_color: black 

paginate: 5
paginate_path: "/page:num/" 

# Build settings
markdown: kramdown

# so simple

plugins:
  - jekyll-feed
# title: Vaishak Belle
# description: Vaishak Belle
# author: Vaishak Belle

# remote_theme: mmistakes/so-simple-theme
# # remote_theme: mmistakes/so-simple-theme
# #skin: "/assets/css/skins/default.css"
